server:
  port: 8080
  servlet:
    context-path: /authentication

spring:
  profiles:
    active: ${PROFILE:}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_authentication
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    encoding: UTF-8

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      base-path: /v1/actuator
      exposure:
        include: actuator, logfile, metrics, health, info

logging:
  file:
    path: .
    name: ms-authentication.log
  level:
    root: info
    org:
      springframework:
        web: info
    com:
      devjansen: debug

